# Generated by Django 6.1 on 2026-09-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_conversation_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="media_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="whatsapp_message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
