# Generated by Django 6.1 on 2026-08-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                (
                    "vertical",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor"),
                            ("lawyer", "Lawyer"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Beirut", max_length=100)),
                (
                    "waba_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("whatsapp_access_token", models.BinaryField(blank=True, null=True)),
                ("whatsapp_connected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "calendar_provider",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("google", "Google"),
                            ("outlook", "Outlook"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("working_hours", models.JSONField(default=dict)),
                (
                    "default_slot_duration_minutes",
                    models.PositiveIntegerField(default=30),
                ),
                ("booking_buffer_minutes", models.PositiveIntegerField(default=0)),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_conversation_quota",
                    models.PositiveIntegerField(default=100),
                ),
                ("system_prompt_overrides", models.JSONField(default=dict)),
                ("language_defaults", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone_number_id"],
                        name="tenants_ten_phone_n_3a4c2e_idx",
                    ),
                    models.Index(
                        fields=["waba_id"], name="tenants_ten_waba_id_b53c41_idx"
                    ),
                ],
            },
        ),
    ]
