# Generated by Django 6.1 on 2026-09-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tenant",
            name="tenants_ten_phone_n_3a4c2e_idx",
        ),
        migrations.RemoveIndex(
            model_name="tenant",
            name="tenants_ten_waba_id_b53c41_idx",
        ),
    ]
