# Generated by Django 6.1 on 2026-09-05 12:57

from django.db import migrations

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_remove_redundant_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="whatsapp_access_token",
            field=core.fields.EncryptedBinaryField(blank=True, null=True),
        ),
    ]
