# Generated by Django 6.1 on 2026-09-05 12:57

from django.db import migrations

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarconnection",
            name="access_token",
            field=core.fields.EncryptedBinaryField(),
        ),
        migrations.AlterField(
            model_name="calendarconnection",
            name="refresh_token",
            field=core.fields.EncryptedBinaryField(),
        ),
    ]
