# Generated by Django 6.1 on 2026-09-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("conversations", "0002_conversation_message"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("scheduled_end__gt", models.F("scheduled_start"))),
                name="booking_end_after_start",
            ),
        ),
    ]
