# Generated by Django 6.1 on 2026-09-05 12:53

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models

import bookings.models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_end_after_start"),
        ("conversations", "0002_conversation_message"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        # btree_gist lets the bigint tenant_id take part in a GiST index.
        BtreeGistExtension(),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_confirmed_booking_start_per_tenant",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", "confirmed")),
                expressions=[
                    ("tenant", "="),
                    (
                        bookings.models.TsTzRange(
                            "scheduled_start",
                            "scheduled_end",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                ],
                name="exclude_overlapping_confirmed_bookings",
            ),
        ),
    ]
