# Generated by Django 6.1 on 2026-09-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_exclude_overlapping_bookings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["scheduled_start", "pk"]},
        ),
    ]
